[project]
name = "odoo-addons-oca-knowledge"
version = "17.0.20240209.0"
dependencies = [
    "odoo-addon-document_knowledge>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
