# Copyright <YEAR(S)> <AUTHOR(S)>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Account Pro QubiQ",
    "summary": "All pro modules for account and invoice ",
    "version": "17.0.1.0.0",
    "category": "Pro",
    "website": "https://www.qubiq.es",
    "author": "QubiQ, Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": [
		"account_banking_mandate",
		"account_chart_update",
		"account_due_list",
		"account_financial_report",
		"account_invoice_fiscal_position_update",
		"account_invoice_merge",
		"account_invoice_refund_link",
		"account_lock_date_update",
		"account_mass_reconcile",
		"account_menu_invoice_refund",
		"account_move_print",
		"account_payment_mode",
		"account_payment_order",
		"account_payment_partner",
		"account_payment_sale",
		"account_payment_term_extension",
		"account_tax_balance",
		"base_bank_from_iban",
		"l10n_es_account_statement_import_n43",
		"l10n_es_aeat",
		"l10n_es_aeat_mod111",
		"l10n_es_aeat_mod115",
		"l10n_es_aeat_mod123",
		"l10n_es_aeat_mod216",
		"l10n_es_aeat_mod303",
		"l10n_es_aeat_mod347",
		"l10n_es_aeat_mod349",
		"l10n_es_aeat_mod390",
		"l10n_es_dua",
		"l10n_es_irnr",
		"l10n_es_mis_report",
		"l10n_es_partner",
		"l10n_es_vat_book",
		"mis_builder",
		"mis_builder_budget",
    ],
    "data": [
    ],
}
